gatling {
  socket {
    connectTimeout = 5000
  }

  charting {
    indicators {
      percentile1 = 50
      percentile2 = 75
      percentile3 = 95
      percentile4 = 99
    }
  }

  http {
    requestTimeout = 10000
  }

  data {
    utcDateTime = true
    enableAnalytics = false
  }
}
