gatling.enterprise.package {
  name = "QuickPizza Performance Tests"
  team = "team_9qhrc8qfsff6dpps4uzu7xxpqa"

  simulations = [
    {
      name = "QuickPizza - Anonymous Smoke"
      simulation = "quickPizza"

      locations = [
        {
          name = "US East - N. Virginia"
          size = 1
          weight = 100
        }
      ]

      useDedicatedIps = false

      parameters {
        ignoreDefaults = true
        systemProperties {
          profile = "smoke"
          baseUrl = "https://quickpizza.grafana.com"
        }
      }

      stopCriteria = [
        {
          type = "meanCpu"
          timeFrameInSeconds = 10
          threshold = {
            maxPercentage = 90
          }
        },
        {
          type = "globalResponseTime"
          timeFrameInSeconds = 10
          threshold = {
            percentile = 95
            maxMilliseconds = 5000
          }
        },
        {
          type = "globalErrorRatio"
          timeFrameInSeconds = 10
          threshold = {
            maxPercentage = 5
          }
        }
      ]
    }
  ]
}
