gatling.enterprise.package {
  id = "package_zo3jqbgrt3nh9gjfbq3jphdzdy"
  name = "QuickPizza Performance Tests"
  team = "team_9qhrc8qfsff6dpps4uzu7xxpqa"

  default {
    simulation {
      locations = [
        {
          name = "US East - N. Virginia"
          size = 1
          weight = 100
        }
      ]

      useDedicatedIps = false

      parameters {
        ignoreDefaults = true
        systemProperties {
          baseUrl = "https://quickpizza.grafana.com"
        }
      }

      stopCriteria = [
        {
          type = "meanCpu"
          timeFrameInSeconds = 10
          threshold = {
            maxPercentage = 90
          }
        },
        {
          type = "globalResponseTime"
          timeFrameInSeconds = 10
          threshold = {
            percentile = 95
            maxMilliseconds = 5000
          }
        },
        {
          type = "globalErrorRatio"
          timeFrameInSeconds = 10
          threshold = {
            maxPercentage = 5
          }
        }
      ]
    }
  }

  simulations = [
    {
      id = "test_e885rruk97b4fpbtpfbxuxtcxa"
      name = "QuickPizza - Anonymous Smoke"
      simulation = "quickPizza"
      parameters {
        systemProperties {
          profile = "smoke"
        }
      }
    },
    {
      name = "QuickPizza - Anonymous Baseline"
      simulation = "quickPizza"
      parameters {
        systemProperties {
          profile = "baseline"
        }
      }
    },
    {
      name = "QuickPizza - Anonymous Light Ramp"
      simulation = "quickPizza"
      parameters {
        systemProperties {
          profile = "light-ramp"
        }
      }
    }
  ]
}
